name: "litequiz"
services:
  backend:
    build:
      context: ./backend-next
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY=bigsecret
      - DATABASE_URL=./database/db.sqlite
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - ./frontend-next/.env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
