version: '3.8'

services:
  backend:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - backend-data:/app/data
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
    ports:
      - '3001:80'

volumes:
  backend-data:
