CREATE TABLE category_score_settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    answer_type TEXT NOT NULL,
    score DECIMAL(6, 2) NOT NULL,
    category_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (category_id) REFERENCES categories(id)
);